[theme]
primaryColor="#9BC4B4"
backgroundColor="#DAE8E2"
secondaryBackgroundColor="#5EA187"
textColor="#09100E"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
